services:
  o2tv-iptvserver:
    container_name: "o2tv-iptvserver"
    image: "ghcr.io/goodbyepavlyi/o2tv-iptvserver:latest"
    ports:
      - "3000:3000"
    volumes:
      - "./Data:/App/Data"
    env_file:
      - ".env"
    restart: "unless-stopped"