services:
  o2tv-iptvserver:
    container_name: "o2tv-iptvserver"
    image: "goodbyepavlyi/o2tv-iptvserver:latest"
    ports:
      - "3000:3000"
    volumes:
      - "./o2tv-iptvserver:/app/data"
    restart: "unless-stopped"