name: Build & Publish Docker image

on:
  push:
    branches:
      - "master"
  workflow_dispatch:

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@main

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: echo RELEASE=$(cat ./package.json | jq -r .version) >> $GITHUB_ENV

      - name: Build & Publish Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            ghcr.io/goodbyepavlyi/o2tv-iptvserver:latest
            ghcr.io/goodbyepavlyi/o2tv-iptvserver:${{ env.RELEASE }}
          labels: |
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
